version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: contas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db" ]
      interval: 5s
      timeout: 5s
      retries: 6
    networks:
      - backend-app
  test:
    image: postgres:latest
    container_name: postgres-test
    environment:
      POSTGRES_DB: contas-test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - backend-app
  app:
    build: .
    container_name: backend-pismo
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contas"
      - "TZ=America/Sao_Paulo"
    networks:
      - backend-app
    depends_on:
      db:
        condition: service_healthy
networks:
  backend-app:
    driver: bridge