version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: contas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  test:
    image: postgres:latest
    container_name: postgres-test
    environment:
      POSTGRES_DB: contas-test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8081:8081"
    depends_on:
      - db
      - test
    restart: on-failure